//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TN.TNM.Common.svcutil_generated
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SAPISoap")]
    public interface SAPISoap
    {
    
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStudentAttendance", ReplyAction="*")]
        getStudentAttendanceResponse getStudentAttendance(getStudentAttendanceRequest request);
    
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStudentAttendance", ReplyAction="*")]
        System.Threading.Tasks.Task<getStudentAttendanceResponse> getStudentAttendanceAsync(getStudentAttendanceRequest request);
    
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNotificationClass", ReplyAction="*")]
        GetNotificationClassResponse GetNotificationClass(GetNotificationClassRequest request);
    
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNotificationClass", ReplyAction="*")]
        System.Threading.Tasks.Task<GetNotificationClassResponse> GetNotificationClassAsync(GetNotificationClassRequest request);
    
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentProfile", ReplyAction="*")]
        GetStudentProfileResponse GetStudentProfile(GetStudentProfileRequest request);
    
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<GetStudentProfileResponse> GetStudentProfileAsync(GetStudentProfileRequest request);
    
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTimeTable", ReplyAction="*")]
        getTimeTableResponse getTimeTable(getTimeTableRequest request);
    
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTimeTable", ReplyAction="*")]
        System.Threading.Tasks.Task<getTimeTableResponse> getTimeTableAsync(getTimeTableRequest request);
    
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContacCenter", ReplyAction="*")]
        GetContacCenterResponse GetContacCenter(GetContacCenterRequest request);
    
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContacCenter", ReplyAction="*")]
        System.Threading.Tasks.Task<GetContacCenterResponse> GetContacCenterAsync(GetContacCenterRequest request);
    
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNews", ReplyAction="*")]
        GetNewsResponse GetNews(GetNewsRequest request);
    
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNews", ReplyAction="*")]
        System.Threading.Tasks.Task<GetNewsResponse> GetNewsAsync(GetNewsRequest request);
    
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DonorPush", ReplyAction="*")]
        DonorPushResponse DonorPush(DonorPushRequest request);
    
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DonorPush", ReplyAction="*")]
        System.Threading.Tasks.Task<DonorPushResponse> DonorPushAsync(DonorPushRequest request);
    
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFullStudent", ReplyAction="*")]
        GetFullStudentResponse GetFullStudent(GetFullStudentRequest request);
    
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFullStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<GetFullStudentResponse> GetFullStudentAsync(GetFullStudentRequest request);
    
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTeacherSummary", ReplyAction="*")]
        GetTeacherSummaryResponse GetTeacherSummary(GetTeacherSummaryRequest request);
    
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTeacherSummary", ReplyAction="*")]
        System.Threading.Tasks.Task<GetTeacherSummaryResponse> GetTeacherSummaryAsync(GetTeacherSummaryRequest request);
    
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProcessGrade", ReplyAction="*")]
        GetProcessGradeResponse GetProcessGrade(GetProcessGradeRequest request);
    
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProcessGrade", ReplyAction="*")]
        System.Threading.Tasks.Task<GetProcessGradeResponse> GetProcessGradeAsync(GetProcessGradeRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStudentAttendanceRequest
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStudentAttendance", Namespace="http://tempuri.org/", Order=0)]
        public getStudentAttendanceRequestBody Body;
    
        public getStudentAttendanceRequest()
        {
        }
    
        public getStudentAttendanceRequest(getStudentAttendanceRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getStudentAttendanceRequestBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phone;
    
        public getStudentAttendanceRequestBody()
        {
        }
    
        public getStudentAttendanceRequestBody(string key, string phone)
        {
            this.key = key;
            this.phone = phone;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStudentAttendanceResponse
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStudentAttendanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public getStudentAttendanceResponseBody Body;
    
        public getStudentAttendanceResponse()
        {
        }
    
        public getStudentAttendanceResponse(getStudentAttendanceResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getStudentAttendanceResponseBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getStudentAttendanceResult;
    
        public getStudentAttendanceResponseBody()
        {
        }
    
        public getStudentAttendanceResponseBody(string getStudentAttendanceResult)
        {
            this.getStudentAttendanceResult = getStudentAttendanceResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNotificationClassRequest
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNotificationClass", Namespace="http://tempuri.org/", Order=0)]
        public GetNotificationClassRequestBody Body;
    
        public GetNotificationClassRequest()
        {
        }
    
        public GetNotificationClassRequest(GetNotificationClassRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNotificationClassRequestBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phone;
    
        public GetNotificationClassRequestBody()
        {
        }
    
        public GetNotificationClassRequestBody(string key, string phone)
        {
            this.key = key;
            this.phone = phone;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNotificationClassResponse
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNotificationClassResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetNotificationClassResponseBody Body;
    
        public GetNotificationClassResponse()
        {
        }
    
        public GetNotificationClassResponse(GetNotificationClassResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNotificationClassResponseBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNotificationClassResult;
    
        public GetNotificationClassResponseBody()
        {
        }
    
        public GetNotificationClassResponseBody(string GetNotificationClassResult)
        {
            this.GetNotificationClassResult = GetNotificationClassResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentProfileRequest
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentProfile", Namespace="http://tempuri.org/", Order=0)]
        public GetStudentProfileRequestBody Body;
    
        public GetStudentProfileRequest()
        {
        }
    
        public GetStudentProfileRequest(GetStudentProfileRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentProfileRequestBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phone;
    
        public GetStudentProfileRequestBody()
        {
        }
    
        public GetStudentProfileRequestBody(string key, string phone)
        {
            this.key = key;
            this.phone = phone;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentProfileResponse
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentProfileResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetStudentProfileResponseBody Body;
    
        public GetStudentProfileResponse()
        {
        }
    
        public GetStudentProfileResponse(GetStudentProfileResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentProfileResponseBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStudentProfileResult;
    
        public GetStudentProfileResponseBody()
        {
        }
    
        public GetStudentProfileResponseBody(string GetStudentProfileResult)
        {
            this.GetStudentProfileResult = GetStudentProfileResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTimeTableRequest
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTimeTable", Namespace="http://tempuri.org/", Order=0)]
        public getTimeTableRequestBody Body;
    
        public getTimeTableRequest()
        {
        }
    
        public getTimeTableRequest(getTimeTableRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTimeTableRequestBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phone;
    
        public getTimeTableRequestBody()
        {
        }
    
        public getTimeTableRequestBody(string key, string phone)
        {
            this.key = key;
            this.phone = phone;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTimeTableResponse
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTimeTableResponse", Namespace="http://tempuri.org/", Order=0)]
        public getTimeTableResponseBody Body;
    
        public getTimeTableResponse()
        {
        }
    
        public getTimeTableResponse(getTimeTableResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTimeTableResponseBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTimeTableResult;
    
        public getTimeTableResponseBody()
        {
        }
    
        public getTimeTableResponseBody(string getTimeTableResult)
        {
            this.getTimeTableResult = getTimeTableResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContacCenterRequest
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContacCenter", Namespace="http://tempuri.org/", Order=0)]
        public GetContacCenterRequestBody Body;
    
        public GetContacCenterRequest()
        {
        }
    
        public GetContacCenterRequest(GetContacCenterRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContacCenterRequestBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phone;
    
        public GetContacCenterRequestBody()
        {
        }
    
        public GetContacCenterRequestBody(string key, string phone)
        {
            this.key = key;
            this.phone = phone;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContacCenterResponse
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContacCenterResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetContacCenterResponseBody Body;
    
        public GetContacCenterResponse()
        {
        }
    
        public GetContacCenterResponse(GetContacCenterResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContacCenterResponseBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetContacCenterResult;
    
        public GetContacCenterResponseBody()
        {
        }
    
        public GetContacCenterResponseBody(string GetContacCenterResult)
        {
            this.GetContacCenterResult = GetContacCenterResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewsRequest
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNews", Namespace="http://tempuri.org/", Order=0)]
        public GetNewsRequestBody Body;
    
        public GetNewsRequest()
        {
        }
    
        public GetNewsRequest(GetNewsRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewsRequestBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
    
        public GetNewsRequestBody()
        {
        }
    
        public GetNewsRequestBody(string key)
        {
            this.key = key;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewsResponse
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewsResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetNewsResponseBody Body;
    
        public GetNewsResponse()
        {
        }
    
        public GetNewsResponse(GetNewsResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewsResponseBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNewsResult;
    
        public GetNewsResponseBody()
        {
        }
    
        public GetNewsResponseBody(string GetNewsResult)
        {
            this.GetNewsResult = GetNewsResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DonorPushRequest
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DonorPush", Namespace="http://tempuri.org/", Order=0)]
        public DonorPushRequestBody Body;
    
        public DonorPushRequest()
        {
        }
    
        public DonorPushRequest(DonorPushRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DonorPushRequestBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phone;
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string content;
    
        public DonorPushRequestBody()
        {
        }
    
        public DonorPushRequestBody(string key, string phone, string content)
        {
            this.key = key;
            this.phone = phone;
            this.content = content;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DonorPushResponse
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DonorPushResponse", Namespace="http://tempuri.org/", Order=0)]
        public DonorPushResponseBody Body;
    
        public DonorPushResponse()
        {
        }
    
        public DonorPushResponse(DonorPushResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DonorPushResponseBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DonorPushResult;
    
        public DonorPushResponseBody()
        {
        }
    
        public DonorPushResponseBody(bool DonorPushResult)
        {
            this.DonorPushResult = DonorPushResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFullStudentRequest
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFullStudent", Namespace="http://tempuri.org/", Order=0)]
        public GetFullStudentRequestBody Body;
    
        public GetFullStudentRequest()
        {
        }
    
        public GetFullStudentRequest(GetFullStudentRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFullStudentRequestBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phone;
    
        public GetFullStudentRequestBody()
        {
        }
    
        public GetFullStudentRequestBody(string key, string phone)
        {
            this.key = key;
            this.phone = phone;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFullStudentResponse
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFullStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetFullStudentResponseBody Body;
    
        public GetFullStudentResponse()
        {
        }
    
        public GetFullStudentResponse(GetFullStudentResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFullStudentResponseBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFullStudentResult;
    
        public GetFullStudentResponseBody()
        {
        }
    
        public GetFullStudentResponseBody(string GetFullStudentResult)
        {
            this.GetFullStudentResult = GetFullStudentResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTeacherSummaryRequest
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTeacherSummary", Namespace="http://tempuri.org/", Order=0)]
        public GetTeacherSummaryRequestBody Body;
    
        public GetTeacherSummaryRequest()
        {
        }
    
        public GetTeacherSummaryRequest(GetTeacherSummaryRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTeacherSummaryRequestBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
    
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime fTime;
    
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime eTime;
    
        public GetTeacherSummaryRequestBody()
        {
        }
    
        public GetTeacherSummaryRequestBody(string key, System.DateTime fTime, System.DateTime eTime)
        {
            this.key = key;
            this.fTime = fTime;
            this.eTime = eTime;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTeacherSummaryResponse
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTeacherSummaryResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetTeacherSummaryResponseBody Body;
    
        public GetTeacherSummaryResponse()
        {
        }
    
        public GetTeacherSummaryResponse(GetTeacherSummaryResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTeacherSummaryResponseBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTeacherSummaryResult;
    
        public GetTeacherSummaryResponseBody()
        {
        }
    
        public GetTeacherSummaryResponseBody(string GetTeacherSummaryResult)
        {
            this.GetTeacherSummaryResult = GetTeacherSummaryResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcessGradeRequest
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProcessGrade", Namespace="http://tempuri.org/", Order=0)]
        public GetProcessGradeRequestBody Body;
    
        public GetProcessGradeRequest()
        {
        }
    
        public GetProcessGradeRequest(GetProcessGradeRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProcessGradeRequestBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phone;
    
        public GetProcessGradeRequestBody()
        {
        }
    
        public GetProcessGradeRequestBody(string key, string phone)
        {
            this.key = key;
            this.phone = phone;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcessGradeResponse
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProcessGradeResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetProcessGradeResponseBody Body;
    
        public GetProcessGradeResponse()
        {
        }
    
        public GetProcessGradeResponse(GetProcessGradeResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProcessGradeResponseBody
    {
    
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetProcessGradeResult;
    
        public GetProcessGradeResponseBody()
        {
        }
    
        public GetProcessGradeResponseBody(string GetProcessGradeResult)
        {
            this.GetProcessGradeResult = GetProcessGradeResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SAPISoapChannel : SAPISoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SAPISoapClient : System.ServiceModel.ClientBase<SAPISoap>, SAPISoap
    {
    
        public SAPISoapClient()
        {
        }
    
        public SAPISoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
        {
        }
    
        public SAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
        {
        }
    
        public SAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
        {
        }
    
        public SAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
        {
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getStudentAttendanceResponse SAPISoap.getStudentAttendance(getStudentAttendanceRequest request)
        {
            return base.Channel.getStudentAttendance(request);
        }
    
        public string getStudentAttendance(string key, string phone)
        {
            getStudentAttendanceRequest inValue = new getStudentAttendanceRequest();
            inValue.Body = new getStudentAttendanceRequestBody();
            inValue.Body.key = key;
            inValue.Body.phone = phone;
            getStudentAttendanceResponse retVal = ((SAPISoap)(this)).getStudentAttendance(inValue);
            return retVal.Body.getStudentAttendanceResult;
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getStudentAttendanceResponse> SAPISoap.getStudentAttendanceAsync(getStudentAttendanceRequest request)
        {
            return base.Channel.getStudentAttendanceAsync(request);
        }
    
        public System.Threading.Tasks.Task<getStudentAttendanceResponse> getStudentAttendanceAsync(string key, string phone)
        {
            getStudentAttendanceRequest inValue = new getStudentAttendanceRequest();
            inValue.Body = new getStudentAttendanceRequestBody();
            inValue.Body.key = key;
            inValue.Body.phone = phone;
            return ((SAPISoap)(this)).getStudentAttendanceAsync(inValue);
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetNotificationClassResponse SAPISoap.GetNotificationClass(GetNotificationClassRequest request)
        {
            return base.Channel.GetNotificationClass(request);
        }
    
        public string GetNotificationClass(string key, string phone)
        {
            GetNotificationClassRequest inValue = new GetNotificationClassRequest();
            inValue.Body = new GetNotificationClassRequestBody();
            inValue.Body.key = key;
            inValue.Body.phone = phone;
            GetNotificationClassResponse retVal = ((SAPISoap)(this)).GetNotificationClass(inValue);
            return retVal.Body.GetNotificationClassResult;
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetNotificationClassResponse> SAPISoap.GetNotificationClassAsync(GetNotificationClassRequest request)
        {
            return base.Channel.GetNotificationClassAsync(request);
        }
    
        public System.Threading.Tasks.Task<GetNotificationClassResponse> GetNotificationClassAsync(string key, string phone)
        {
            GetNotificationClassRequest inValue = new GetNotificationClassRequest();
            inValue.Body = new GetNotificationClassRequestBody();
            inValue.Body.key = key;
            inValue.Body.phone = phone;
            return ((SAPISoap)(this)).GetNotificationClassAsync(inValue);
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetStudentProfileResponse SAPISoap.GetStudentProfile(GetStudentProfileRequest request)
        {
            return base.Channel.GetStudentProfile(request);
        }
    
        public string GetStudentProfile(string key, string phone)
        {
            GetStudentProfileRequest inValue = new GetStudentProfileRequest();
            inValue.Body = new GetStudentProfileRequestBody();
            inValue.Body.key = key;
            inValue.Body.phone = phone;
            GetStudentProfileResponse retVal = ((SAPISoap)(this)).GetStudentProfile(inValue);
            return retVal.Body.GetStudentProfileResult;
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetStudentProfileResponse> SAPISoap.GetStudentProfileAsync(GetStudentProfileRequest request)
        {
            return base.Channel.GetStudentProfileAsync(request);
        }
    
        public System.Threading.Tasks.Task<GetStudentProfileResponse> GetStudentProfileAsync(string key, string phone)
        {
            GetStudentProfileRequest inValue = new GetStudentProfileRequest();
            inValue.Body = new GetStudentProfileRequestBody();
            inValue.Body.key = key;
            inValue.Body.phone = phone;
            return ((SAPISoap)(this)).GetStudentProfileAsync(inValue);
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getTimeTableResponse SAPISoap.getTimeTable(getTimeTableRequest request)
        {
            return base.Channel.getTimeTable(request);
        }
    
        public string getTimeTable(string key, string phone)
        {
            getTimeTableRequest inValue = new getTimeTableRequest();
            inValue.Body = new getTimeTableRequestBody();
            inValue.Body.key = key;
            inValue.Body.phone = phone;
            getTimeTableResponse retVal = ((SAPISoap)(this)).getTimeTable(inValue);
            return retVal.Body.getTimeTableResult;
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getTimeTableResponse> SAPISoap.getTimeTableAsync(getTimeTableRequest request)
        {
            return base.Channel.getTimeTableAsync(request);
        }
    
        public System.Threading.Tasks.Task<getTimeTableResponse> getTimeTableAsync(string key, string phone)
        {
            getTimeTableRequest inValue = new getTimeTableRequest();
            inValue.Body = new getTimeTableRequestBody();
            inValue.Body.key = key;
            inValue.Body.phone = phone;
            return ((SAPISoap)(this)).getTimeTableAsync(inValue);
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetContacCenterResponse SAPISoap.GetContacCenter(GetContacCenterRequest request)
        {
            return base.Channel.GetContacCenter(request);
        }
    
        public string GetContacCenter(string key, string phone)
        {
            GetContacCenterRequest inValue = new GetContacCenterRequest();
            inValue.Body = new GetContacCenterRequestBody();
            inValue.Body.key = key;
            inValue.Body.phone = phone;
            GetContacCenterResponse retVal = ((SAPISoap)(this)).GetContacCenter(inValue);
            return retVal.Body.GetContacCenterResult;
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetContacCenterResponse> SAPISoap.GetContacCenterAsync(GetContacCenterRequest request)
        {
            return base.Channel.GetContacCenterAsync(request);
        }
    
        public System.Threading.Tasks.Task<GetContacCenterResponse> GetContacCenterAsync(string key, string phone)
        {
            GetContacCenterRequest inValue = new GetContacCenterRequest();
            inValue.Body = new GetContacCenterRequestBody();
            inValue.Body.key = key;
            inValue.Body.phone = phone;
            return ((SAPISoap)(this)).GetContacCenterAsync(inValue);
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetNewsResponse SAPISoap.GetNews(GetNewsRequest request)
        {
            return base.Channel.GetNews(request);
        }
    
        public string GetNews(string key)
        {
            GetNewsRequest inValue = new GetNewsRequest();
            inValue.Body = new GetNewsRequestBody();
            inValue.Body.key = key;
            GetNewsResponse retVal = ((SAPISoap)(this)).GetNews(inValue);
            return retVal.Body.GetNewsResult;
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetNewsResponse> SAPISoap.GetNewsAsync(GetNewsRequest request)
        {
            return base.Channel.GetNewsAsync(request);
        }
    
        public System.Threading.Tasks.Task<GetNewsResponse> GetNewsAsync(string key)
        {
            GetNewsRequest inValue = new GetNewsRequest();
            inValue.Body = new GetNewsRequestBody();
            inValue.Body.key = key;
            return ((SAPISoap)(this)).GetNewsAsync(inValue);
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DonorPushResponse SAPISoap.DonorPush(DonorPushRequest request)
        {
            return base.Channel.DonorPush(request);
        }
    
        public bool DonorPush(string key, string phone, string content)
        {
            DonorPushRequest inValue = new DonorPushRequest();
            inValue.Body = new DonorPushRequestBody();
            inValue.Body.key = key;
            inValue.Body.phone = phone;
            inValue.Body.content = content;
            DonorPushResponse retVal = ((SAPISoap)(this)).DonorPush(inValue);
            return retVal.Body.DonorPushResult;
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DonorPushResponse> SAPISoap.DonorPushAsync(DonorPushRequest request)
        {
            return base.Channel.DonorPushAsync(request);
        }
    
        public System.Threading.Tasks.Task<DonorPushResponse> DonorPushAsync(string key, string phone, string content)
        {
            DonorPushRequest inValue = new DonorPushRequest();
            inValue.Body = new DonorPushRequestBody();
            inValue.Body.key = key;
            inValue.Body.phone = phone;
            inValue.Body.content = content;
            return ((SAPISoap)(this)).DonorPushAsync(inValue);
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetFullStudentResponse SAPISoap.GetFullStudent(GetFullStudentRequest request)
        {
            return base.Channel.GetFullStudent(request);
        }
    
        public string GetFullStudent(string key, string phone)
        {
            GetFullStudentRequest inValue = new GetFullStudentRequest();
            inValue.Body = new GetFullStudentRequestBody();
            inValue.Body.key = key;
            inValue.Body.phone = phone;
            GetFullStudentResponse retVal = ((SAPISoap)(this)).GetFullStudent(inValue);
            return retVal.Body.GetFullStudentResult;
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetFullStudentResponse> SAPISoap.GetFullStudentAsync(GetFullStudentRequest request)
        {
            return base.Channel.GetFullStudentAsync(request);
        }
    
        public System.Threading.Tasks.Task<GetFullStudentResponse> GetFullStudentAsync(string key, string phone)
        {
            GetFullStudentRequest inValue = new GetFullStudentRequest();
            inValue.Body = new GetFullStudentRequestBody();
            inValue.Body.key = key;
            inValue.Body.phone = phone;
            return ((SAPISoap)(this)).GetFullStudentAsync(inValue);
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetTeacherSummaryResponse SAPISoap.GetTeacherSummary(GetTeacherSummaryRequest request)
        {
            return base.Channel.GetTeacherSummary(request);
        }
    
        public string GetTeacherSummary(string key, System.DateTime fTime, System.DateTime eTime)
        {
            GetTeacherSummaryRequest inValue = new GetTeacherSummaryRequest();
            inValue.Body = new GetTeacherSummaryRequestBody();
            inValue.Body.key = key;
            inValue.Body.fTime = fTime;
            inValue.Body.eTime = eTime;
            GetTeacherSummaryResponse retVal = ((SAPISoap)(this)).GetTeacherSummary(inValue);
            return retVal.Body.GetTeacherSummaryResult;
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetTeacherSummaryResponse> SAPISoap.GetTeacherSummaryAsync(GetTeacherSummaryRequest request)
        {
            return base.Channel.GetTeacherSummaryAsync(request);
        }
    
        public System.Threading.Tasks.Task<GetTeacherSummaryResponse> GetTeacherSummaryAsync(string key, System.DateTime fTime, System.DateTime eTime)
        {
            GetTeacherSummaryRequest inValue = new GetTeacherSummaryRequest();
            inValue.Body = new GetTeacherSummaryRequestBody();
            inValue.Body.key = key;
            inValue.Body.fTime = fTime;
            inValue.Body.eTime = eTime;
            return ((SAPISoap)(this)).GetTeacherSummaryAsync(inValue);
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetProcessGradeResponse SAPISoap.GetProcessGrade(GetProcessGradeRequest request)
        {
            return base.Channel.GetProcessGrade(request);
        }
    
        public string GetProcessGrade(string key, string phone)
        {
            GetProcessGradeRequest inValue = new GetProcessGradeRequest();
            inValue.Body = new GetProcessGradeRequestBody();
            inValue.Body.key = key;
            inValue.Body.phone = phone;
            GetProcessGradeResponse retVal = ((SAPISoap)(this)).GetProcessGrade(inValue);
            return retVal.Body.GetProcessGradeResult;
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetProcessGradeResponse> SAPISoap.GetProcessGradeAsync(GetProcessGradeRequest request)
        {
            return base.Channel.GetProcessGradeAsync(request);
        }
    
        public System.Threading.Tasks.Task<GetProcessGradeResponse> GetProcessGradeAsync(string key, string phone)
        {
            GetProcessGradeRequest inValue = new GetProcessGradeRequest();
            inValue.Body = new GetProcessGradeRequestBody();
            inValue.Body.key = key;
            inValue.Body.phone = phone;
            return ((SAPISoap)(this)).GetProcessGradeAsync(inValue);
        }
    }
}